baseURL: https://blog.gustavclausen.com/
languageCode: en-us
title: Blog of Gus
theme: "PaperMod"
paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
deployment:
  targets:
    - url: "s3://blog.gustavclausen.com?region=eu-west-1"
      cloudFrontDistributionID: "E37TXUQ5MDRH1E"
params:
  env: production
  title: Blog of Gus
  description: "Blog of Gus"
  keywords: [Blog]
  author: Gus
  DateFormat: "January 2, 2006"
  defaultTheme: light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.ico"
    favicon32x32: "/favicon-32x32.ico"
  profileMode:
    enabled: false
  homeInfoParams:
    Title: "Hello fellow \U0001F44B"
    Content: |
      Welcome to my blog!

      My name is Gustav but call me Gus if you like (*it tends to be easier to pronounce*).
      I'm an engineer with an academic and professional background in Software Engineering,
      and currently specializing in Platform- and Site Reliability Engineering.

      I use this blog to share my thoughts and findings related to my work and interests
      that are worth sharing. Hopefully, it will be useful for others working in the field.
  socialIcons:
    - name: other
      url: "https://gustavclausen.com"
    - name: github
      url: "https://github.com/gustavclausen"
    - name: linkedin
      url: "https://linkedin.com/in/gustavclausen"
    - name: twitter
      url: "https://twitter.com/gustavkc"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/15681515/gustav-clausen"
    - name: reddit
      url: "https://www.reddit.com/user/gkc97"
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=gustavclausen"
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 10
pygmentsUseClasses: true # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
